# Generated by Django 5.0.1 on 2024-01-05 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KanDo', '0002_alter_task_task_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='task_slug',
            field=models.CharField(max_length=200, verbose_name='Sla'),
        ),
    ]
