# Generated by Django 5.0.1 on 2024-01-05 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('KanDo', '0004_alter_task_task_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='task_slug',
        ),
    ]
