# Generated by Django 5.0.1 on 2024-01-05 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KanDo', '0005_remove_task_task_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.IntegerField(choices=[(0, 'To-do'), (1, 'Doing'), (3, 'Finished'), (4, 'Not finished'), (5, 'Aborted')], default=0),
        ),
    ]
